### PR TITLE
Euler voronoi

### PR DESCRIPTION
**Pull request by eyal0**
Use eulerian paths for voronoi.

This is a rewrite of much of surface_vectorial.cpp.

## Non-Voronoi changes
In the case of non-voronoi, very little is changed.  In fact, the output is usually identical to before.  The difference happens only in the case of contentions and are small: Instead of not milling, milling will happen for the contention and a warning is given to the user.  It's not clear to me if it's better to not mill and risk not isolating or better to mill and risk making traces too small/ cutting traces.  Either is bad news.  For PCBs with enough clearance, it doesn't matter.

## Voronoi changes.
The big change is in voronoi.  Instead of making rings around each equipotential net, it just draws lines.  The method is like this:

1. Find all edges of the voronoi graph that divides nets as before.
2. Find [Eulerian paths](https://en.wikipedia.org/wiki/Eulerian_path) along all those edges.
3. If extra_passes are specified, widen those path and make more paths.

In the normal cases without extra_passes, this mills about half as much material because it doesn't mill each path twice.  The milling follows the same route as before.  extra_passes is now supported, where before it wasn't, using half `offset` for each new pass, same as non-voronoi above.

## New features
* If offset is 0 but multiple passes are specified, it will remill along the same path.
* Voronoi works even if an outline (edge cuts) isn't provided.  A [convex hull](https://en.wikipedia.org/wiki/Convex_hull) of all milling is used as the border.
* Contentions are highlighted in red in the .svg output for easier debugging.
* More sample gerbers added for testing.

### CODE REVIEW

**Comment by eyal0** [comment]
This fixes https://github.com/pcb2gcode/pcb2gcode/issues/60 .

**Comment by eyal0** [comment]
@corna In case you're curious, I have an explanation for why you needed this: https://github.com/pcb2gcode/pcb2gcode/blob/master/voronoi.cpp#L106

Sometimes a shape that needs to be milled, after voronoi, creates extra holes:
image
The large green surrounding region is just one piece with a little gap in it in the center.  When converting to voronoi regions, you get this:

image

Zooming in on the middle:
image

You can see that there is a little black line connecting the dark and light purple.  In that section, the outer perimeter of the voronoi region traced back over itself.  A better way to handle that is to let the two sides merge together and treat the inner section as a hole in the polygon.

Now you know!

**Comment by corna** [comment]
Thanks for the explanation and for the commits.

Let me know when it's ready.

**Comment by eyal0** [comment]
This PR has gotten way too big. I'm going to split it up into smaller pieces and make separate PRs.

**Pull request closed without merging**
