### PR TITLE
add error for positive --zcut

### PR DESCRIPTION
**Pull request by cho45**
positive zcut produces invalid large loop

https://github.com/pcb2gcode/pcb2gcode/blob/master/ngc_exporter.cpp#L259
```
> const unsigned int steps_num = ceil(-mill->zwork / cutter->stepsize);

mill->zwork = 1
cutter->stepsize = 1
(unsigined int)ceil(-1)
```

### CODE REVIEW

**Comment by corna** [comment]
Thanks for pointing it out
Why a warning and not an error? I don't think there is a valid use case with zcut > 0

**Comment by cho45** [comment]
I think this should be error. But I let the behaviour to same as --zwork.

If error is better, I will define `ERR_NEGATIVEZWORK` and append `exit(ERR_NEGATIVETOLERANCE)` line to this patch.

**Comment by corna** [comment]
Yes, an error is better

**Comment by corna** [comment]
Thanks

**Pull request merged**
