### PR TITLE
Lift mill between steps to zsafe if path is not a closed loop

### PR DESCRIPTION
**Pull request by hannesweisbach**
If path is not a closed loop moving to the beginning of the path at any milling depth might move across copper areas.

This is really ugly because it duplicates a lot of code. I'm also not sure if there exists a similiar problem for contour cutting (but pcb2gcode might require the outline to be a closed loop, I don't remember exactly)

Proposed fix for #477.

### CODE REVIEW

**Comment by hannesweisbach** [comment]
PS: Is there a way for me to fix CI? Python 2 is, I think, deprecated by now. brew has python@3.7 and python@3.8 currently available.

**Comment by hannesweisbach** [comment]
Ok, I factored out the XY-move code to a separate function. I like it this way a lot better ;)

**Comment by hannesweisbach** [comment]
The current implementation of lift is correct, but it might lift too often, slowing down machine operation. I wonder if `bg::covered_by` can be used instead of `bg::equals`, i.e. instead of
```!bg::equals(end, start)```
use 
```! covered_by(line_type_fp(end, start), path)```

**Comment by hannesweisbach** [comment]
I think now it also handles the autoleveller correctly.

**Comment by eyal0** [comment]
Sorry that I haven't had time to look at this.

CI will test this well and also the autoleveller. I will try to make time for this project.

**Comment by hannesweisbach** [comment]
No worries, I do it in my free time also.

**Pull request merged**
