### PR TITLE
Compile with recent versions of glibmm using current gcc/g++ version.

### PR DESCRIPTION
**Pull request by mirage335**
Recent versions of glibmm seem to require C++11 support, while current GCC/G++ versions do not enable this by default. Adding a CFLAG is apparently necessary in this situation.

Arch Linux package versions responsible for the build failure are as follows.
glibmm 2.46.1-1
gcc 5.2.0-2

### CODE REVIEW

**Comment by corna** [comment]
Adding std=c++11 directly to CFLAGS is not a good idea, as the configure script can't figure out if the compiler actually supports C++11 (see the [Travis CI log](https://travis-ci.org/pcb2gcode/pcb2gcode/jobs/91149022#L350)).
A better solution is to use the [AX_CXX_COMPILE_STDCXX_11](https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx_11.html) flag. Unfortunately, if compiled with C++11, Boost requires std=gnu++11 or -fext-numeric-literals, or it will fail with errors like
`````
/usr/include/boost/math/constants/constants.hpp:329:3: error: unable to find numeric literal operator ‘operator""Q’
   BOOST_DEFINE_MATH_CONSTANT(one_div_ln_phi, 2.078086921235027537601322606117795767e+00, "2.078086921235027537601322606117795767742192267783283480278139921919743869285
   ^
`````
so you should use AX_CXX_COMPILE_STDCXX_11([ext],[mandatory]), that forces gnu++11
Since the travis script should be changed accordingly (Travis' GCC does not support C++11), I'll work on it

**Comment by corna** [comment]
I've added C++11 in commit c4413c61115181faca8d5c548ea0b6f03e4140cc
Can you please test it?

**Comment by EdgarJRobles** [comment]
uname command -->Linux  3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Hi, I compile throught gitclone files and this what I got 
./configure: line 15277: AX_CXX_COMPILE_STDCXX_11: command not found
./configure: line 15281: syntax error near unexpected token `-fext-numeric-literals,'
./configure: line 15281: `AX_CHECK_COMPILE_FLAG(-fext-numeric-literals,'
I hope it is useful

**Comment by corna** [comment]
I'm fixing right now the readme, newer versions of pcb2gcode require the package autoconf-archive (see #24)
Can you install autoconf-archive and retry?

**Comment by corna** [comment]
Fixed in commit 4897d928dea3297bc8d50828fdef97a63863311f
Thanks

**Comment by EdgarJRobles** [comment]
it works¡ thanks
configure: creating ./config.status
config.status: creating Makefile
config.status: creating man/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

**Pull request closed without merging**
