### PR TITLE
Add support for global millproject file

### PR DESCRIPTION
**Pull request by dzervas**
I hacked support for a global millproject file. It would be very useful for me as I don't have to redefine everything every time and can just over-write option in a per-project manner and I think a lot of other people have the same workflow/need. Would you be interested in such a functionality?

My C++ knowledge is lacking (and I think it shows even from a 5 line contribution) so I'd like any pointers to make this contribution passable (probably split the homedir expansion in a different function somewhere outside of `options.cpp`, add man page reference, add it to the readme/wiki, add unit tests, etc.)

### CODE REVIEW

**Comment by eyal0** [comment]
Your code looks nice.  It's an interesting idea to be sure. I'm wondering if it's the right way to go about it, though...

My worry is that the `.millproject` is an unexpected feature.  Like, I worry that no one would ever figure it out.  It isn't mentioned in the help at all.  It's not very discoverable.

In fact, the whole idea of having the name `millproject` file is kind of crap.  Why that name?  How is a user supposed to know that `millproject` is the magic file name that gets read.  It's a hard-coded value.

What if the config file name were programmable and the default were `millproject`.  In which case, everything would work like it already work.  So we'd add a flag called, say `--config`, and it would be default `--config=millproject`.

We could make the parameter not be a string but a vector of strings.  So you could write, `--config=~/.millproject,millproject`, and it would read them in that order.  Or put in as many files as you want.  Also, we could print out an error message if a file that is specified is not found.  This solves all our problems around `$HOME` or whatever other variables because we don't need to know about them at all.  This solution would cover all file systems.

In the case of `--config` not specified, the default is `millproject` and a missing `millproject` file is not an error.  If `--config` is specified then it *is* an error for any of the files in the list to be missing.  The files are read in order, with the latter file's options overriding the former file's options.  And of course, all command-line options override file options.

To keep it simple, command-line options *always* override the file ones, even if they come before it.  For example: `--x=true --config=millproject`.  I don't want to deal with `x=3` in the millproject overriding the command-line option.  That would be surprising and confusing!  So probably I would emit a warning or an error if any options are listed before the `--config`.  `--config` must come before any other options.

So that's an idea.  I like that it's flexible.  For you, it would solve your problem but you'd need to add `--config=~/.millproject,millproject` to your usage of pcb2gcode.  Or you could store the millproject wherever you want, with whatever name you want.

What do you think of this idea?  Good?  Bad?  Annoying?

**Comment by dzervas** [comment]
Well of course if this PR is to be considered, I'll mention it everywhere possible. In `--help`, in man pages, in the readme. For me it was quite natural to try to create a `~/.millproject` file the first time that I was playing with pcb2gcode - as a Linux user though, my weird UX can vary by a mile vs other users.

Actually a vector `--config` would make total sense and maybe defaulting it to `~/.millproject,millproject` would make sense. The last file should take precedence so:
- `~/.millproject`: `x=1`
- `millproject`: `x=2`

You end up with `x=2`

Of course CLI arguments overpower everything else. Thankfully it's actually quite hard to break that functionality code-wise so we're good.

Include is another awesome idea so that you can use a set of profiles for different machines or different materials. But I think that the vectored `--config` should get implemented anyway and the include get implemented later on.

**Comment by eyal0** [comment]
#607 Implements the feature.  It was actually not too hard to do.  I also added some tests.

I did not implement config files including other config files.  I don't think that it would be so useful and definitely there are issues like with recursive includes and stuff that would be complex to sort out.  Also, the precedence would be confusing with how boost program options works.  Maybe later on if there is some need one day.

Do you think that it makes more sense for the files to be listed left to right or right to left?  Which do you prefer:

1. `--config=~/.millproject,millproject`
2. `--config=millproject,~/.millproject`

**Comment by dzervas** [comment]
woah that was fast!

I'd say left-to-right, as we write.
Closing this PR as it's no longer needed

**Comment by eyal0** [comment]
So I'm clear, you think that number 1 is better or number 2? https://github.com/pcb2gcode/pcb2gcode/pull/606#issuecomment-1010178418

**Comment by dzervas** [comment]
number 1

**Comment by eyal0** [comment]
Done.  Please try it out and let me know if it works okay for you.  Thanks!

**Comment by dzervas** [comment]
Works awesome! :tada: 
Thank you very much!!

**Pull request closed without merging**
