### PR TITLE
Add support for code coverage

### PR DESCRIPTION
**Pull request by eyal0**
Code coverage allows checking how well unit tests exercise the code.

Instructions are in the README.  When building without code coverage, there is no effect.

### CODE REVIEW

**Comment by corna** [comment]
autoconf-archive is already a requirement, there shouldn't be the need to ship ax_code_coverage.m4.

**Comment by eyal0** [comment]
Yes!  I removed it.  Thanks.

**Comment by eyal0** [comment]
I tried to remove that file but Travis CI failed.  Not sure why!

**Comment by corna** [comment]
autoconf-archive in Trusty is v2013.11.01, while ax_code_coverage [has been added in v2014.10.15](https://github.com/peti/autoconf-archive/commit/eaefa29a5ba070fd4f5b704c992ffcedf4e83e1c#diff-9b17df31da3fcbb3b226863933edb6b2). I'm afraid we have to include it.

**Comment by eyal0** [comment]
Ah, okay.  Well, up to you.  I think that code coverage is nice to have but it's not critical.

**Comment by corna** [comment]
Let's include it of course, it's just an extra m4 macro. Go ahead.

**Pull request merged**
