### PR TITLE
Only mirror absolute

### PR DESCRIPTION
**Pull request by eyal0**
Remove `mirror-absolute=false` because only `mirror-absolute=true` makes sense for two-sided boards.  And for one-sided boards, there is no difference.

`zero-start` allows choosing if the board will be milled near the zero of the machine or if the zero of the gerber files will be respected.  In either case, when flipping the board over, it should be flipped along the y-axis.

### CODE REVIEW

**Comment by eyal0** [comment]
This is based on https://github.com/pcb2gcode/pcb2gcode/pull/91

This fixes https://github.com/pcb2gcode/pcb2gcode/issues/87

**Comment by eyal0** [comment]
I tested many combinations of the following options:

* tile-x
* cut-size
* drill-side
* zero-start
* milldrill

Depending on those options, the output is affected.  I checked that the output looks reasonable for as many combinations as possible.

**Comment by eyal0** [comment]
I can see that, in the current code before this PR, the drilling is screwed up.

Here's the config:

```
back=multivibrator-B.Cu.gbr
front=multivibrator-B.Cu.gbr
drill=multivibrator.drl
outline=multivibrator-Edge.Cuts.gbr

mirror-absolute=true
zero-start=true
tile-x=1
cut-side=back
drill-side=back
vectorial=true
mill-feed=360 in/min
mill-speed=200rotations/second
voronoi=false
zwork=-0.04inch
drill-feed=30
drill-speed=12000
milldrill=true
onedrill=false
zdrill=-1.6
cut-feed=100
cut-infeed=0.1
cut-speed=10000
cutter-diameter=0.8
milldrill-diameter=0.01
zbridges=-0.6000
zcut=-0.13
fill-outline=true
zsafe=0.08
zchange=1.0
```

Here is the output:

image

The drill file doesn't look aligned for neither back nor front.  Maybe this is what @deirdreobyrne saw in https://github.com/pcb2gcode/pcb2gcode/issues/64 ?

**Comment by laurivosandi** [comment]
Hello, well these updates have broken pcb2gcode for me, for dual sided PCB-s on one side the coordinates are now growing positive and on the other side they grow to negative direction. This makes flipping impossible. I used to have symmetric mounting points on the PCB and flipping around the center of the board made sense.

**Comment by eyal0** [comment]
How did you used to flip the PCB?  Can you explain your process?

You say that you had symmetric mounting points on the PCB.  Were those points drilled by pcb2gcode output?  In which files?

Could you let me know your process?  Like, was it first drill.ngc, then back.ngc, then flip, then front.ngc, then...?

**Comment by laurivosandi** [comment]
Hello, I've elaborated about my process here in the past: https://lauri.vosandi.com/2016/07/linuxcnc.html

**Comment by eyal0** [comment]
Okay that was very useful, thank you. So on your pcb design in kicad, you added mounting holes to the design? And you made sure that they are four and evenly spaced from the center of the board? Then the drill file press those holes in the board and you enlarge them with a hand drill, then flip and like them up with bolts.

All that is correct?

For what you do, the PCB is flipped around the center of the mounting points and that is the same as the center of the design for your design. But for some designs, the center of the mounting holes is not the same as the center of the design.

For my pcb rig, I am flipping over the PCB not from the center of the design but for the center of the FR4 raw material. The reason is because I hold the FR4 in place by its edges. If the PCB center line is different from the FR4 center line, this is a problem because after I flip the PCB, the sometimes the FR4 no longer fits on the machine!

An easy solution is for you to set the x for flipping. In your design just take the average x for the left and right mounting points and give it to pcb2gcode.

--mirror-axis=50mm

For example.

**Comment by eyal0** [comment]
Also please read this: https://github.com/pcb2gcode/pcb2gcode/wiki/Options:-Two-sided-PCB-and-offsets

**Pull request merged**
