### PR TITLE
Make the cut-infeed more realistic in the gerbv examples

### PR DESCRIPTION
**Pull request by eyal0**
I ran:

`grep -l -R cut-infeed=100 | xargs sed -i s/cut-infeed=100/cut-infeed=0.19/`

And then:

`./integration_tests.py --fix --add`

This is related to #224

### CODE REVIEW

**Comment by eyal0** [comment]
This is still not great because it's in inches and not mm but it's a first step, I guess.

**Comment by chaotix-** [comment]
This does not really fix the problem, I was talking about. The slots and holes are cut 1.6inches = 40.64mm deep. I have attached a picture of the expected slots-milldrill.ngc to show what I mean. zdrill=-1.6 was probably meant in mm. So it should be something like zdrill=-0.063in.

slots-milldrill

**Comment by eyal0** [comment]
Yeah, that's true.

I originally added the project based on my experiments with pcb2gcode.  Only later did I realize the whole metric vs imperial stuff and fix it in my project, but not in the examples.

Does it matter that much for just a unit test?  This is just for coverage and integration testing, not to actually drill.

**Comment by chaotix-** [comment]
You are right of course. It doesn't really hurt.

I was just using them to check if the results were sane and what I wanted when doing the slot implementation. It was just a bit confusing and harder to see if the generated toolpath was good.

**Pull request merged**
