### PR TITLE
Millinfeed

### PR DESCRIPTION
**Pull request by pci06**
Hello,
this pull request add mill-infeed option, allowing multi-pass for small and fragile bits.

Regards.

### CODE REVIEW

**Comment by eyal0** [comment]
It's hard to read this with all the whitespace changes.  Can you undo those?  They make the diff look much larger than it really is and create difficulty down the line when merging changes.  I know that the whitespace isn't consistent in the file so just make each change resemble the surrounding code. 
 Thanks!

Also, I see that all the CI tests are failing.  I'll re-run those, let's see if it helps.

**Comment by pci06** [comment]
Hello,
sorry for this little mess in commits ;)
May be you know it,  you can [ignore white space changes while reviewing](https://github.blog/2018-05-01-ignore-white-space-in-code-review/).
I've checked the CI results and it fails while setting up "termcolor" (```pip install...```) in "Run integration tests" (not found container to run the CI locally)

**Comment by eyal0** [comment]
The errors from pip during install aren't the real problem, it's that the integration tests are failing.  At the bottom of the test log, it says:

```
Ran 65 tests in 19.575s

FAILED (failures=37)

***
Run one of these:
./integration_tests.py --fix
./integration_tests.py --fix --add
```

Looks like the order of some of the outputs got changed.

```
@@ -4173,9 +4173,9 @@
 
 G00 X3.09705 Y-3.50000 ( rapid move to begin. )
 G01 F180.00000
-G01 Z-0.04000
-G04 P0 ( dwell for no time -- G64 should not smooth over this point )
-G01 F360.00000
+G04 P0 ( dwell for no time -- G64 should not smooth over this point )
+G01 F360.00000
+G01 Z-0.04000 ( Mill infeed 0.04000 )
 G01 X3.09705 Y-3.50000
 G01 X3.09705 Y-2.45000
 G01 X3.09836 Y-2.44754
```

The Z change comes after the G04 and the G01 now and there is a new comment about mill infeed.

I'll look through the diffs and see what I can do to help this merge along.

**Comment by eyal0** [comment]
I pushed a new version that removes all the whitespace changes.  There are still some issues around the testing.  Also, this code will break the autoleveller.  If you prefer, I can make my changes in a different branch for you to see and then incorporate yourself or we can work together inside this branch.

**Comment by pci06** [comment]
Hello,
whenever you want. I will adapt.
Both solutions are fine for me.

**Comment by eyal0** [comment]
I made a version that should be compatible with yours but also fixes the autoleveller code.  Can you try it out?

I'll also add an integration test for the new option.  If you have example gerbers, I can use those.  Or I will make my own, no problem.

Thanks!

**Comment by pci06** [comment]
Hello,
Yes, I'll try it soon.

**Pull request merged**
