### PR TITLE
New build_voronoi

### PR DESCRIPTION
**Pull request by eyal0**
The new build_voronoi routine solves the problem described here: https://github.com/pcb2gcode/pcb2gcode/pull/79#issuecomment-353953181

I also added a unit test for build_voronoi.  The test can be run at https://github.com/pcb2gcode/pcb2gcode/commit/e46fb27b43b2aad18e6316003eb7cd1dc8e97b0d and then at https://github.com/pcb2gcode/pcb2gcode/commit/1964032805fdfdf4ea3a8917122e16681f5d7ace and the generated svg outputs compared, showing how it solves the problem.

The difference can be seen here, the new is on the left, the old on the right:
image

In the center and in the top left of the old image, there is a little voronoi line that divides two copper sections that are connected together elsewhere.

### CODE REVIEW

**Comment by eyal0** [comment]
@corna This is part of the big change that I proposed before, just the voronoi fix.  Let me know if you want to look at it first before I merge it.

**Comment by corna** [comment]
Tomorrow I'll have a look

**Comment by corna** [comment]
It seems ok to me, feel free to merge (after squashing all the commits in few relevant ones).

**Comment by corna** [comment]
Well, these commits are ok, just capitalize the first letters and add a detailed commit message for 1964032.

**Pull request merged**
