### PR TITLE
Allow options with units

### PR DESCRIPTION
**Pull request by eyal0**
Currently, all options that have a dimension (length, speed, etc) are supplied dimensionless and the flag -metric determines if the input is millimeters or inches.

This can be confusing because it's not clear that the units of speed are per minute (and not per second, for example).  Also, some users might prefer to specify some parameters in inchs and some in mm or in thou (which is more common than inch).

Rather than require the user to the conversions, we allow the user to add dimensions.  Such as:

```
mill-feed=360 in/min
mill-speed=200rotations/second
zwork=-0.04inch
```

Extra spaces are ignored and there are reasonable synonyms for each (ifor example in/inch/inches).  Most reasonable strings can be parsed and when parsing fails, a useful error message is printed:

For example, trying to parse `dogs/min`

```
Didn't recognize units of length: dogs
Error parsing configuration file "millproject": the argument for option 'mill-feed' is invalid
```

Parsing `seconds` where a length is expected:
```
Didn't recognize units of length: seconds
Error parsing configuration file "millproject": the argument for option 'zwork' is invalid
```

When there are no dimensions specified, the default is the original behavior.

### CODE REVIEW

**Comment by eyal0** [comment]
@corna I think that this is a nice feature and can be less confusing than unitless inputs.  I had the idea when I looked at [this PR](https://github.com/pcb2gcode/pcb2gcode/pull/71/files#diff-68cebd5bddb0fd616f204a6d9d810bc3R86).  It has some weird scaling manipulation on line 86 that could be avoided if the user could just specify units.

I used regex so the regex libraries would need to be compiled into `https://sourceforge.net/projects/pcb2gcode/files/pcb2gcode/boost/boost_${BOOST}_amd64.tar.xz/download`.

What do you think?

**Comment by corna** [comment]
It's a great feature, well done! Feel free to merge it when you think it's ready (after squashing the commits in few relevant ones).

Is the Regex library really needed? Don't get me wrong, if it is needed I have no problem adding it as dependency, but I was wondering if it is possible to work without it.

**Comment by eyal0** [comment]
Thanks!  I think that this will add clarity to millproject files.

I use the regex in order to parse the units.  For example, someone might type: `50mm/second` or 
`50 mm /   second` with tabs.  Using regex lets me handle removing the whitespace and finding the "/" as a divider easily.

I could do it without.  The only units that I've found are length, speed, and rotational speed, so I only need to deal with stripping whitespace ,finding the end of the digits and the start of the units, and splitting on "/".

The advantage of using regex is that it's easy and flexible.  The disadvantage is that we need to link a new library, which adds to the size of the binary.  Without regex, the binary is smaller but I'd have to write the string parsing myself, which will make the code a longer and potentially leave more room for bugs.

The parsing isn't so complicated so I'm fine with either solution.  Is there a third solution?

What do you think?

**Comment by corna** [comment]
Try to implement it without the regex library: if you realize that it's too complex, it takes too long or it's not a good solution we'll use Boost Regex. Do you find it reasonable?

**Pull request closed without merging**
